# Tensorflow AND 연산

In [3]:
import tensorflow as tf ### 기본 라이브러리 불러오기
import numpy as np
sess = tf.Session()

In [5]:
### y = wx+b

x = tf.placeholder(tf.float32, shape=[None, 2])
t = tf.placeholder(tf.float32, shape=[None, 1])

w = tf.Variable(tf.truncated_normal([2, 1]))
b = tf.Variable(tf.zeros([1]))

y = tf.nn.sigmoid(tf.matmul(x, w)+b)   ### 연산방법 정의 x*w + b

In [6]:
cross_ent = -tf.reduce_mean(t*tf.log(y)+(1-t)*tf.log(1-y))   ### Error function

In [7]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
train_step = optimizer.minimize(cross_ent)   ### grd dcnt 를 최소화

In [8]:
correct_pred = tf.equal(tf.to_float(tf.greater(y, 0.5)), t)   ### y와 0.5의 값 비교 ( T, F 반환 )

### 연산 (한 바퀴 돌림)

In [9]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])   ### data 입력 (x1, x2, t)
Y = np.array([[0], [0], [0], [1]])

init = tf.global_variables_initializer()   ### initialize 필요
sess.run(init)

In [10]:
prob = y.eval(session=sess, feed_dict={x:X})   ### y값 계산
print(prob)

[[ 0.5       ]
 [ 0.44472229]
 [ 0.7078073 ]
 [ 0.65987563]]


In [11]:
classified = correct_pred.eval(session=sess, feed_dict={x:X, t:Y})   ### 결과랑 비교해서 맞는지 판단
print(classified)

[[ True]
 [ True]
 [False]
 [False]]


In [12]:
print(sess.run(w))   ### w, b 값 계산
print(sess.run(b))

[[ 0.88475823]
 [-0.22201839]]
[ 0.]


### 학습

In [13]:
### 옵티를 minimize

for epoch in range(1000):   ### 1000번 계산한다.
    sess.run(train_step, feed_dict={x:X, t:Y})
    if epoch % 100 == 0:   ### 이건 그냥 잘 돌아가는지 판단하려고...
        print("epoch =", epoch)

epoch = 0
epoch = 100
epoch = 200
epoch = 300
epoch = 400
epoch = 500
epoch = 600
epoch = 700
epoch = 800
epoch = 900


In [14]:
classified = correct_pred.eval(session=sess, feed_dict={x:X, t:Y})   ### 제대로 분류되는지 판단
print(classified)

[[ True]
 [ True]
 [ True]
 [ True]]


In [15]:
prob = y.eval(session=sess, feed_dict={x:X})
print(prob)

[[ 0.01986753]
 [ 0.00482403]
 [ 0.00818679]
 [ 0.00197006]]


In [16]:
print(sess.run(w))   ### 값 출력
print(sess.run(b))

[[-0.89841205]
 [-1.43070841]]
[-3.89860082]


In [17]:
### linear 이기 때문에 XOR은 잘 나오지 않는다.