# Python Basic on Numpy

In [2]:
import numpy as np
print(np.__version__)

1.12.1


### np.array

In [2]:
a=np.array([1, 2, 3])
print('a=', a)
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)

a= [1 2 3]
<class 'numpy.ndarray'>
(3,)
int64
1


In [3]:
b=np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.shape, b.dtype, b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3) int64 2


In [4]:
a=np.array([[[1.5, 2, 3], [4, 5, 6]], [[3, 1, 5], [5, 6, 7]]])
print(a)

[[[ 1.5  2.   3. ]
  [ 4.   5.   6. ]]

 [[ 3.   1.   5. ]
  [ 5.   6.   7. ]]]


In [5]:
a=np.array([[1+2j, 3], [5, 6-3j]], dtype=complex)   ### i로는 안되고 j로 써야 함!!
print('a= \n', a)
print(a.shape)
print(a.dtype)

a= 
 [[ 1.+2.j  3.+0.j]
 [ 5.+0.j  6.-3.j]]
(2, 2)
complex128


### zeros, ones, full, eye, arange, linspace, reshape, concatenate

In [6]:
a=np.zeros((2, 2))   ### 2*2의 영행렬
print(a)

b=np.ones((1, 2))   ### 1*2의 1행렬
print(b)

c=np.full((2, 2), 7)   ### 2*2의 7행렬
print(c)

d=np.eye(3)   ### 3*3 의 identity
print(d)

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [10]:
pi=np.pi

a=np.linspace(0, 2, 9)
print(a)
b=np.linspace(0, 2*pi, 10)
print(b)

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]
[ 0.          0.6981317   1.3962634   2.0943951   2.7925268   3.4906585
  4.1887902   4.88692191  5.58505361  6.28318531]


In [7]:
a=np.arange(6)   ### 0부터 6개 
print(a)

b=np.arange(0, 120, 20)   ### 0부터 120까지 20의 간격으로
print(b)

c=np.arange(0.1, 2, 0.1)   ### 0부터 1, 2까지 0.1의 간격으로
print(c)

d=np.arange(0, 2, 0.3)   ### 0부터 2까지 0.3의 간격으로
print(d)

[0 1 2 3 4 5]
[  0  20  40  60  80 100]
[ 0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5
  1.6  1.7  1.8  1.9]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8]


In [11]:
a=np.zeros(6)
print(a, a.shape)

aa=a.reshape(6, 1)
print(aa, aa.shape)

b=a.reshape(1, 6)
print(b, b.shape)

bb=b.flatten()
print(bb, bb.shape)

[ 0.  0.  0.  0.  0.  0.] (6,)
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] (6, 1)
[[ 0.  0.  0.  0.  0.  0.]] (1, 6)
[ 0.  0.  0.  0.  0.  0.] (6,)


In [12]:
a1=np.arange(6).reshape(3, 2)
a2=np.linspace(10, 60, 6).reshape(3, 2)
print(a1, '\n', a2)

[[0 1]
 [2 3]
 [4 5]] 
 [[ 10.  20.]
 [ 30.  40.]
 [ 50.  60.]]


In [15]:
a=np.concatenate((a1, a2))
print(a, '\n')
b=np.concatenate((a1, a2), axis=0)   ### axis=0 이 기본.
print(b, '\n')
c=np.concatenate((a1, a2), axis=1)
print(c, '\n')

[[  0.   1.]
 [  2.   3.]
 [  4.   5.]
 [ 10.  20.]
 [ 30.  40.]
 [ 50.  60.]] 

[[  0.   1.]
 [  2.   3.]
 [  4.   5.]
 [ 10.  20.]
 [ 30.  40.]
 [ 50.  60.]] 

[[  0.   1.  10.  20.]
 [  2.   3.  30.  40.]
 [  4.   5.  50.  60.]] 



### Random Number

In [16]:
np.random.seed(1)
a=np.random.randint(0, 10, 100) 0부터 9까지 100개의 random 추출 
print(a)
np.random.randint?   ### 도움말 참고.

[5 8 9 5 0 0 1 7 6 9 2 4 5 2 4 2 4 7 7 9 1 7 0 6 9 9 7 6 9 1 0 1 8 8 3 9 8
 7 3 6 5 1 9 3 4 8 1 4 0 3 9 2 0 4 9 2 7 7 9 8 6 9 3 7 7 4 5 9 3 6 8 0 2 7
 7 9 7 3 0 8 7 7 1 1 3 0 8 6 4 5 6 2 5 7 8 4 4 7 7 4]


### element, submatrix

In [18]:
a=np.array([5, 8, 3])
print(a[0])
print(a[1])
print(a[2])

5
8
3


In [4]:
a=np.arange(10)
print(a)
print(a[:2])   ### 처음 ~ 2번째
print(a[3:])   ### 3번째 ~ 끝
print(a[:-1])   ### 끝에 1개 -
print(a[:-2])   ### 끝에 2개 -
print(a[5:6])   ### 5 ~ (5-1)번째 -
print(a[1:9:3])   ### 1부터 9번째까지 3번째마다
print(a[::2])   ### 2번씩 건너뛰어서
a[9]=100
print(a)
a[1:3]=[-10, 10]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7]
[5]
[1 4 7]
[0 2 4 6 8]
[  0   1   2   3   4   5   6   7   8 100]
[  0 -10  10   3   4   5   6   7   8 100]


In [5]:
b=np.array([-5, 5])
a[6:8]=b
print(a)
print(b)

[  0 -10  10   3   4   5  -5   5   8 100]
[-5  5]


In [6]:
a=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
b=a[:, 1]
c=a[:, 1:2]
print(b.shape)
print(c.shape)

(3,)
(3, 1)


In [13]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)
b=np.array([0, 2, 0, 1])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]


In [20]:
print(a[:, b])
print(a[range(4), b])   ###두개 헷갈리지 않기!!

[ 1  6  7 11]


In [21]:
a[np.arange(4), b]+=10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Copy

In [22]:
a=np.arange(6)
b=a
c=a[:]
d=a.copy()

print(a, '\n', b, '\n', c, '\n' , d)

a[0]=1000
print(a, '\n', b, '\n', c, '\n' , d)   ###copy일 때는 초기값 고정!

[0 1 2 3 4 5] 
 [0 1 2 3 4 5] 
 [0 1 2 3 4 5] 
 [0 1 2 3 4 5]
[1000    1    2    3    4    5] 
 [1000    1    2    3    4    5] 
 [1000    1    2    3    4    5] 
 [0 1 2 3 4 5]


In [23]:
a=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b=a
c=a.copy()
d=a[:2, 1:3]

d[0, 0]=1000
print(a, '\n', b, '\n', c, '\n', d)

[[   1 1000    3    4]
 [   5    6    7    8]
 [   9   10   11   12]] 
 [[   1 1000    3    4]
 [   5    6    7    8]
 [   9   10   11   12]] 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
 [[1000    3]
 [   6    7]]


### Transpose, boolean

In [24]:
a=np.arange(6).reshape(2, 3)
print(a)
print(a.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [25]:
x=np.array([[1, 2], [3, 4]])
print(x.T.T)

[[1 2]
 [3 4]]


In [26]:
a=np.array([[1, 2], [3, 4], [5, 6]])
bool=(a>2)
print(bool)
print(a[bool])
print(a[a>0])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[1 2 3 4 5 6]
