# Python Matrix Operations

In [12]:
import numpy as np
print(np.__version__)

1.12.1


### Elementwise operations

In [5]:
x=np.array([[1, 2], [3, 4]], dtype=np.float64)
y=np.array([[5, 6], [7, 8]], dtype=np.float64)
print(A, '\n\n', B, '\n\n', A.shape, '\n\n', B.shape)

[[ 1.  2.]
 [ 3.  4.]] 

 [[ 5.  6.]
 [ 7.  8.]] 

 (2, 2) 

 (2, 2)


In [10]:
print(x+y, '\n')
print(x-y, '\n')
print(x*y, '\n')
print(x/y)

[[  6.   8.]
 [ 10.  12.]] 

[[-4. -4.]
 [-4. -4.]] 

[[  5.  12.]
 [ 21.  32.]] 

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [9]:
print(x**2, y**2, '\n')
print(y**x, '\n')
print(np.sqrt(x), '\n')
print(np.exp(x), '\n')
print(np.sin(x))

[[  1.   4.]
 [  9.  16.]] [[ 25.  36.]
 [ 49.  64.]] 

[[    5.    36.]
 [  343.  4096.]] 

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]] 

[[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]] 

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]] 



### Inner Product / Matrix Vector Product / Matrix-Matirx Product

In [16]:
A=np.array([[1, 2], [3, 4]])
B=np.array([[5, 6], [7, 8]])
print(A, A.shape, '\n')

v=np.array([9, 10])
w=np.array([11, 12])
print(v, v.shape)

[[1 2]
 [3 4]] (2, 2) 

[ 9 10] (2,)


In [17]:
vrow=v.reshape(1, 2)   # row vector [v1, v2]
vcol=v.reshape(2, 1)   # column vector [v1, v2].T

In [18]:
### v, w의 내적계산
print(v.dot(w))
print(w.dot(v))   # 순서는 상관없다.
print(np.dot(v, w))

219
219
219


In [19]:
print(vrow.dot(w))
print(vcol.dot(w))  # 실행안됨
print(w.dot(vrow))  # 실행안됨
print(w.dot(vcol))

[219]


ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [22]:
print(np.dot(vrow, w))
print(np.dot(vcol,w))  # 실행안됨
print(np.dot(w, vrow))  # 실행안됨
print(np.dot(w, vcol))

### 이렇게 해봐도 마찬가지...
### 앞에 column vector 이 오거나 뒤에 row vector 가 오면 안된다..

[219]
[219]


In [34]:
print(A, v, '\n')   # A, v의 값
print(A.dot(v), '\n')
print(np.dot(A, v), np.dot(A, v).shape, '\n')
print(A*v, '\n')
print(v.dot(A), '\n')
print(np.dot(v, A), np.dot(v, A).shape, '\n')
print(v*A)

[[1 2]
 [3 4]] [ 9 10] 

[29 67] 

[29 67] (2,) 

[[ 9 20]
 [27 40]] 

[39 58] 

[39 58] (2,) 

[[ 9 20]
 [27 40]]


In [35]:
print(A*vcol)
print(vcol*A)
print(A*vrow)
print(vrow*A)

[[ 9 18]
 [30 40]]
[[ 9 18]
 [30 40]]
[[ 9 20]
 [27 40]]
[[ 9 20]
 [27 40]]


In [36]:
print(A.dot(B))
print(np.dot(A, B))
print(np.matmul(A, B))   # 다 행렬곱

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Broadcasting

In [39]:
x=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v=np.array([1, 0, 1])
print(x, v, '\n')
print(x+v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] [1 0 1] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [40]:
y=np.empty_like(x)

for i in range(4):
    y[i, :]=x[i, :]+v   # 이런식으로 계산할 수도 있음

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [41]:
vv=np.tile(v, (4, 1))
print(vv, '\n')   # 또 이런식으로도 가능...
print(x+vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [44]:
x=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v=np.array([[1, 2, 3, 4]])

z=x+v.T

print(z)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


# Basics Commands in Statistics

### min, max, sum, cumsum

In [46]:
F=np.arange(12).reshape(3, 4)
print(F)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
print(F.sum(), '\n')
print(np.sum(F), '\n')
print(F.sum(axis=0), '\n')   # 아래로
print(F.sum(axis=1), '\n')   # -> 옆으로
print(np.sum(F, axis=0), '\n')   # 아래로
print(np.sum(F, axis=1), '\n')   # -> 옆으로

66 

66 

[12 15 18 21] 

[ 6 22 38] 

[12 15 18 21] 

[ 6 22 38] 



In [54]:
print(F.min(), '\n')
print(F.max(axis=0), '\n')
print(F.max(axis=1), '\n')
print(np.max(F, axis=1), '\n')
print(F.cumsum(axis=0))

0 

[ 8  9 10 11] 

[ 3  7 11] 

[ 3  7 11] 

[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


### mean, average, std, var, cov, corrcoef

In [57]:
a=np.arange(10)
print(a.mean())
print(np.mean(a))
print(np.average(a))   # a.average() 는 안됨...
print(a.std())
print(np.std(a))
print(a.var())
print(np.var(a))

4.5
4.5
4.5
2.87228132327
2.87228132327
8.25
8.25


In [59]:
pi=np.pi
z=2*pi*np.random.rand(1000)
x=np.sin(z)
y=np.cos(z)

In [61]:
x_mean=np.mean(x)
x_var=np.var(x)
x_std=np.std(x)

y_mean=np.mean(y)
y_var=np.var(y)
y_std=np.std(y)

print(x_var)
print(y_var, '\n')


print(np.cov(x, y, bias='True'))   # covariance
print(np.corrcoef(x, y))   # correlation

0.477192224563
0.522287448191 

[[ 0.47719222 -0.01296368]
 [-0.01296368  0.52228745]]
[[ 1.        -0.0259673]
 [-0.0259673  1.       ]]


In [67]:
print(np.mean(z))
print(np.var(z))

z_bar=np.mean(z)
z_sq=np.sum((z-z_bar)**2)
print(z_sq/1000)   ### var() 는 N으로 나눈 것

3.13622866112
3.28077508841
3.28077508841


### sort

In [69]:
a=np.array([[1, 4], [3, 1]])
print(a, '\n')

b=np.sort(a)
print(b, '\n')   # 내림차순

c=np.sort(a, axis=None)
print(c, '\n')   # 전체를 다 내림차순

d=np.sort(a, axis=0)
print(d)

[[1 4]
 [3 1]] 

[[1 4]
 [1 3]] 

[1 1 3 4] 

[[1 1]
 [3 4]]
