# Basics for Tensorflow

### Basic data type and commands

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(1234, dtype=tf.int32)   ### 상수저장
b = tf.constant(5000)
total = a+b
print(a)
print(b)
print(total)   ### 이렇게 해서는 값이 출력이 안됨...

Tensor("Const:0", shape=(), dtype=int32)
Tensor("Const_1:0", shape=(), dtype=int32)
Tensor("add:0", shape=(), dtype=int32)


In [3]:
sess = tf.Session()

In [4]:
print(sess.run(total))   ### 이 작업을 반드시 해야만 값이 출력이 됨
print(sess.run([a, b]))

6234
[1234, 5000]


In [5]:
vec = tf.random_uniform(shape = (3,))
out1 = vec+1
out2 = vec+2
print(sess.run(vec))
print(sess.run(vec))   #결과값이 다르다, (랜덤)
print(sess.run(out1))
print(sess.run(out2))
print(sess.run((out1, out2)))

[ 0.16736257  0.22105455  0.22447443]
[ 0.10523033  0.09197569  0.53415024]
[ 1.69410849  1.00133932  1.13768053]
[ 2.87762523  2.99764013  2.27601433]
(array([ 1.77458704,  1.21513557,  1.145962  ], dtype=float32), array([ 2.77458715,  2.21513557,  2.145962  ], dtype=float32))


In [6]:
import tensorflow as tf
sess=tf.Session()

a = tf.constant(321)
b = tf.constant(4000)

add_op = a+b

print(add_op)   # 이러면 결과가 안뜸...
print(sess.run(add_op))   #이런식으로 계산해야함

4321
Tensor("add_3:0", shape=(), dtype=int32)


In [7]:
### Exercise
### a=10, b=40인 constant일 때, c=(20a-3b)를 계산하는 코드

import tensorflow as tf

a = tf.constant(10)
b = tf.constant(40)

sess = tf.Session()
print(sess.run(20*a-3*b))

80


### Placeholder

In [8]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a+b

In [9]:
print(sess.run(adder_node, feed_dict={a:3, b:4.5}))  ### 해당하는 a, b 값마다 adder_node 계산
print(sess.run(adder_node, feed_dict={a:[1,3], b:[2, 4]}))   ### a, b가 벡터일때도 동일

7.5
[ 3.  7.]


In [10]:
add_and_triple = adder_node*3
print(sess.run(add_and_triple, feed_dict={a:4, b:2}))   ### 이런식으로 바로 넣어도 되고

c = sess.run(add_and_triple, feed_dict={a:3, b:4.5})   ### 이렇게 미리 계산해서 넣어도 된다.
print(c)

18.0
22.5


In [11]:
a = tf.placeholder(tf.int32,[3])   ### data size가 3으로 고정

b = tf.constant(2)
x2_op = a*b

r1 = sess.run(x2_op, feed_dict={a:[1, 2, 3]})
r2 = sess.run(x2_op, feed_dict={a:[4, 5, 6]})
print(r1, r2)

[2 4 6] [ 8 10 12]


In [12]:
a = tf.placeholder(tf.int32,[None])   ### data size 없음
b = tf.constant(10)
x10_op = a*b

r1 = sess.run(x10_op, feed_dict={a:[1, 2, 3, 4, 5]})
r2 = sess.run(x10_op, feed_dict={a:[10, 20]})
print(r1, r2)

[10 20 30 40 50] [100 200]


In [13]:
### Exercise 

a = tf.placeholder(tf.float64, [None])
b = tf.placeholder(tf.float64, [1])

c = a*b+2.5

sess.run(c, feed_dict={a:[1, 3, 7, 9], b:[4]})

array([  6.5,  14.5,  30.5,  38.5])

### Variable

In [ ]:
import tensorflow as tf
sess = tf.Session()

In [14]:
a = tf.constant(100)
b = tf.constant(50)
v = tf.Variable(0)

v = a+b

print(sess.run(v))
print(sess.run(a))

150
100


In [15]:
a = tf.constant(100)
b = tf.placeholder(tf.int32)
v = tf.Variable(0)

v = a+b
### out = sess.run(v, feed_dict={b:[50, 100]})

print(sess.run(v, feed_dict={b:[50, 100]}))

[150 200]


In [16]:
### Example 4

import tensorflow as tf
sess = tf.Session()


a = tf.Variable(100)    ### 얘가 변수면 좀 단계가 하나 더 필요...
b = tf.placeholder(tf.int32)
v = tf.Variable(0)

v = a+b

init = tf.global_variables_initializer()   ### variable 일 경우 이걸 반드시 해야지 값이 입력된다. (변수 initialize)
sess.run(init)

print(sess.run(v, feed_dict={b:[50, 100]}))

[150 200]


In [17]:
### Example 5

W = tf.Variable([0.3], dtype=tf.float64)
b = tf.Variable([-0.3], dtype=tf.float64)
x = tf.placeholder(tf.float64)

linear_model = W*x + b

init = tf.global_variables_initializer()   ### initialize 필요

sess.run(init)
print(sess.run(W))
print(sess.run(b))

print(sess.run(linear_model, {x:[1, 2, 3, 4]}))   ### x일 때마다의 model값 출력

[ 0.3]
[-0.3]
[ 0.   0.3  0.6  0.9]


In [18]:
import numpy as np

In [19]:
X_train = np.array([1, 2, 3, 4])

print(sess.run(linear_model, {x:X_train}))

[ 0.   0.3  0.6  0.9]


In [20]:
out = linear_model.eval(session=sess, feed_dict={x:X_train})
print(out)

[ 0.   0.3  0.6  0.9]


In [21]:
### Exercise

import tensorflow as tf
sess = tf.Session()

x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)
a = tf.Variable(2)
b = tf.Variable(3)
L = tf.Variable(0)
N = tf.constant(3)

L = tf.reduce_sum((a*x+b-y)**2)/N   ### y = ax+b의 error 계신

init = tf.global_variables_initializer()   ### initialize 필요
sess.run(init)


print(sess.run(L, feed_dict={x:[1, 2, 3], y:[2, 0, -1]}))

52.6666666667


In [22]:
a = tf.Variable(100)
b = tf.placeholder(tf.int32)
v = tf.Variable(0)

v = a+b

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(v, {b:10}))
print(sess.run(v, {b:[20, 30]}))

110
[120 130]


In [23]:
fixA = tf.assign(a, 50)   ### a 를 50으로 변경
sess.run(fixA)

print(sess.run(v, {b:10}))
print(sess.run(v, {b:[20, 30]}))

60
[70 80]


In [24]:
### Exercise
### W를 -0.9, b를 1.2로 변경한 후 x=[1, 2, 3, 4], y=[0, -1, -2, -3]값에 대하여 loss를 계산하여라.

import tensorflow as tf
sess = tf.Session()

W = tf.Variable(0, dtype=tf.float64)   ### 임의의 초기값 0 설정
b = tf.Variable(0, dtype=tf.float64)
init = tf.global_variables_initializer()   ### initialize
sess.run(init)

print(sess.run(W))   ### 원래 값 0, 0 출력
print(sess.run(b))

fix_W = tf.assign(W, -0.9)   ### 값 변경
fix_b = tf.assign(b, 1.2)
sess.run(fix_W)
sess.run(fix_b)

print(sess.run(fix_W))   ### 변경해준 값
print(sess.run(fix_b))

x = tf.placeholder(tf.float64)
y = tf.placeholder(tf.float64)
fix_W = tf.Variable([-0.9], dtype=tf.float64)
fix_b = tf.Variable([1.2], dtype=tf.float64)

loss = tf.reduce_sum((fix_W*x+fix_b-y)**2)/4   ### y = ax+b의 error 계신

init = tf.global_variables_initializer()   ### initialize 필요
sess.run(init)


print(sess.run(loss, feed_dict={x:[1, 2, 3, 4], y:[0, -1, -2, -3]}))   ### 출력

0.0
0.0
-0.9
1.2
0.215


In [25]:
import tensorflow as tf
sess = tf.Session()

In [26]:
W = tf.Variable([0.3], dtype=tf.float64)
b = tf.Variable([-0.3], dtype=tf.float64)
x = tf.placeholder(tf.float64)

y = tf.placeholder(tf.float64)

linear_model = W*x+b
squared_deltas = tf.square(linear_model-y)
loss = tf.reduce_sum(squared_deltas)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(linear_model, {x:[1, 2, 3, 4], y:[0, -1, -2, -3]}))
print(sess.run(loss, {x:[1, 2, 3, 4], y:[0, -1, -2, -3]}))

[ 0.   0.3  0.6  0.9]
23.66
