# Basics for Tensorflow

### Basic data type and commands

In [ ]:
import tensorflow as tf

In [ ]:
a = tf.constant(1234, dtype=tf.int32)   ### 상수저장
b = tf.constant(5000)
total = a+b
print(a)
print(b)
print(total)   ### 이렇게 해서는 출력이 안됨...

In [ ]:
sess = tf.Session()

In [ ]:
print(sess.run(total))   ### 이런식으로 해야 출력이 됨
print(sess.run([a, b]))

In [ ]:
vec = tf.random_uniform(shape = (3,))
out1 = vec+1
out2 = vec+2
print(sess.run(vec))
print(sess.run(vec))   #결과값이 다르다,
print(sess.run(out1))
print(sess.run(out2))
print(sess.run((out1, out2)))

In [ ]:
import tensorflow as tf
sess=tf.Session()

a=tf.constant(321)
b=tf.constant(4000)

add_op = a+b

res = sess.run(add_op)   #이런식으로 계산해야함
print(res)
print(add_op)   # 이러면 결과가 안뜸...

In [ ]:
### Exercise
### a=10, b=40인 constant일 때, c=(20a-3b)를 계산하는 코드

import tensorflow as tf

a = tf.constant(10)
b = tf.constant(40)

sess = tf.Session()
print(sess.run(20*a-3*b))

### Placeholder

In [ ]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a+b

In [ ]:
print(sess.run(adder_node, feed_dict={a:3, b:4.5}))
print(sess.run(adder_node, feed_dict={a:[1,3], b:[2, 4]}))

In [ ]:
add_and_triple = adder_node*3
print(sess.run(add_and_triple, feed_dict={a:4, b:2}))

c = sess.run(add_and_triple, feed_dict={a:3, b:4.5})
print(c)

In [ ]:
a=tf.placeholder(tf.int32,[3])   ### data size가 3으로 고정

b=tf.constant(2)
x2_op=a*b

r1=sess.run(x2_op, feed_dict={a:[1, 2, 3]})
r2=sess.run(x2_op, feed_dict={a:[4, 5, 6]})
print(r1, r2)

In [ ]:
a=tf.placeholder(tf.int32,[None])   ### data size 없음
b=tf.constant(10)
x10_op=a*b

r1=sess.run(x10_op, feed_dict={a:[1, 2, 3, 4, 5]})
r2=sess.run(x10_op, feed_dict={a:[10, 20]})
print(r1, r2)

In [ ]:
### Exercise 

a=tf.placeholder(tf.float64, [None])
b=tf.placeholder(tf.float64, [1])

c=a*b+2.5

sess.run(c, feed_dict={a:[1, 3, 7, 9], b:[4]})

### Variable

In [ ]:
a = tf.constant(100)
b = tf.constant(50)
v = tf.Variable(0)

v = a+b

print(sess.run(v))
print(sess.run(a))

In [ ]:
a = tf.constant(100)
b = tf.placeholder(tf.int32)
v = tf.Variable(0)

v = a+b
out = sess.run(v, feed_dict={b:[50, 100]})

print(out)

In [2]:
import tensorflow as tf

a=tf.Variable(100)
b=tf.placeholder(tf.int32)
v=tf.Variable(0)

v = a+b

sess = tf.Session()

init = tf.global_variables_initializer()   ### 이게 뭘까?
sess.run(init)

print(sess.run(v, feed_dict={b:[50, 100]}))

[150 200]


In [5]:
W = tf.Variable([0.3], dtype=tf.float64)
b = tf.Variable([-0.3], dtype=tf.float64)
x = tf.placeholder(tf.float64)

linear_model = W*x+b

init = tf.global_variables_initializer()

sess.run(init)
print(sess.run(W))
print(sess.run(b))

[ 0.3]
[-0.3]


In [6]:
print(sess.run(linear_model, feed_dict={x:[1, 2, 3, 4]}))

[ 0.   0.3  0.6  0.9]


In [9]:
import numpy as np

X_train = np.array([1, 2, 3, 4])

print(sess.run(linear_model, feed_dict={x:X_train}))

[ 0.   0.3  0.6  0.9]


In [11]:
out = linear_model.eval(session=sess, feed_dict={x:X_train})
print(out)

[ 0.   0.3  0.6  0.9]


In [ ]:
### Exercise


In [14]:
a = tf.Variable(100)
b = tf.placeholder(tf.int32)
v = tf.Variable(0)

v = a+b

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(v, {b:10}))
print(sess.run(v, {b:[20, 30]}))

110
[120 130]


In [15]:
fixA = tf.assign(a, 50)
sess.run(fixA)

print(sess.run(v, {b:10}))
print(sess.run(v, {b:[20, 30]}))

60
[70 80]


In [ ]:
### Exercise


In [17]:
W = tf.Variable([0.3], dtype=tf.float64)
b = tf.Variable([-0.3], dtype=tf.float64)
x = tf.placeholder(tf.float64)

y = tf.placeholder(tf.float64)

linear_model = W*x+b
squared_deltas = tf.square(linear_model-y)
loss = tf.reduce_sum(squared_deltas)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(linear_model, {x:[1, 2, 3, 4], y:[0, -1, -2, -3]}))
print(sess.run(loss, {x:[1, 2, 3, 4], y:[0, -1, -2, -3]}))

[ 0.   0.3  0.6  0.9]
23.66
