# 타이타닉

### 데이터 숫자로 바꾸기

In [1]:
import numpy as np
import pandas as pd

In [2]:
dat = pd.read_csv("train.csv")   ### 불러오기

In [3]:
dat.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
### 이름 저장

colnames = dat.columns

In [5]:
### Sex 변환, male : 0, female : 

for i in range(np.shape(dat)[0]):
    if(dat.loc[i, 'Sex'] == 'male'):
        dat.loc[i, 'Sex'] = 0
    elif(dat.loc[i, 'Sex'] == 'female'):
        dat.loc[i, 'Sex'] = 1

In [6]:
### Embarked 변환, C : 1, Q : 2, S : 3

for i in range(np.shape(dat)[0]):
    if(dat.loc[i, 'Embarked'] == 'C'):
        dat.loc[i, 'Embarked'] = 1
    elif(dat.loc[i, 'Embarked'] == 'Q'):
        dat.loc[i, 'Embarked'] = 2
    elif(dat.loc[i, 'Embarked'] == 'S'):
        dat.loc[i, 'Embarked'] = 3

In [7]:
### Name 삭제
### Ticket 삭제
### Cabin 삭제

dat = np.array(dat)
dat = dat[:, (1, 2, 4, 5, 6, 7, 9, 11)]

In [8]:
### 완ㅋ성ㅋ

dat = pd.DataFrame(dat)
dat.columns = colnames[(1, 2, 4, 5, 6, 7, 9, 11),]

dat[:10]

Survived Pclass Sex  Age SibSp Parch     Fare Embarked
0        0      3   0   22     1     0     7.25        3
1        1      1   1   38     1     0  71.2833        1
2        1      3   1   26     0     0    7.925        3
3        1      1   1   35     1     0     53.1        3
4        0      3   0   35     0     0     8.05        3
5        0      3   0  NaN     0     0   8.4583        2
6        0      1   0   54     0     0  51.8625        3
7        0      3   0    2     3     1   21.075        3
8        1      3   1   27     0     2  11.1333        3
9        1      2   1   14     1     0  30.0708        1

In [9]:
dat.to_csv('train_fix.csv', index = False)

### 결측치 제거

In [10]:
### Age 결측치 177 개
### NaN을 버리자... 712 개만 사용

dat = dat.dropna(how='any')

In [11]:
X = np.array(dat)

Y = X[:,0]
X = X[:, 1:8]

Y = Y.reshape(-1, 1)
##astype(np.float64)

print(X[0:10,:], '\n')
print(Y[0:10])

[[3 0 22.0 1 0 7.25 3]
 [1 1 38.0 1 0 71.2833 1]
 [3 1 26.0 0 0 7.925 3]
 [1 1 35.0 1 0 53.1 3]
 [3 0 35.0 0 0 8.05 3]
 [1 0 54.0 0 0 51.8625 3]
 [3 0 2.0 3 1 21.075 3]
 [3 1 27.0 0 2 11.1333 3]
 [2 1 14.0 1 0 30.0708 1]
 [3 1 4.0 1 1 16.7 3]] 

[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]


### Deep learning

In [12]:
import tensorflow as tf

In [13]:
hid_1 = 9
hid_2 = 4


x = tf.placeholder(tf.float32, shape=[None, 7])   ### shape(-1, 2)
t = tf.placeholder(tf.float32, shape=[None, 1])


w1 = tf.Variable(tf.truncated_normal([7, hid_1]))
b1 = tf.Variable(tf.zeros([hid_1]))
z1 = tf.nn.sigmoid(tf.matmul(x, w1)+b1)   ### Hidden 1


w2 = tf.Variable(tf.truncated_normal([hid_1, hid_2]))
b2 = tf.Variable(tf.zeros([hid_2]))
z2 = tf.nn.sigmoid(tf.matmul(z1, w2)+b2)   ### Hidden 2


w3 = tf.Variable(tf.truncated_normal([hid_2, 1]))
b3 = tf.Variable(tf.zeros([1]))
y = tf.nn.sigmoid(tf.matmul(z2, w3)+b3)   ### Output

In [14]:
cross_ent = -tf.reduce_mean(t*tf.log(y)+(1-t)*tf.log(1-y))   ### Error function 계산

lr = 0.1   ### learning rate = 0.1
optimizer = tf.train.GradientDescentOptimizer(lr)
train_step = optimizer.minimize(cross_ent)

In [15]:
correct_pred = tf.equal(tf.to_float(tf.greater(y, 0.5)), t)   ### y와 0.5의 값 비교 ( T, F 반환 )

In [16]:
init = tf.global_variables_initializer()   ### initialize 필요
sess = tf.Session()
sess.run(init)

### 10000번 반복수행

In [17]:
for epoch in range(10000):   ### 10000번 계산한다.
    sess.run(train_step, feed_dict={x:X, t:Y})
    if epoch % 1000 == 0:   ### 이건 그냥 잘 돌아가는지 판단하려고...
        print("epoch =", epoch)

epoch = 0
epoch = 1000
epoch = 2000
epoch = 3000
epoch = 4000
epoch = 5000
epoch = 6000
epoch = 7000
epoch = 8000
epoch = 9000


In [18]:
classified = correct_pred.eval(session=sess, feed_dict={x:X, t:Y})   ### 제대로 분류되는지 판단

print('True :', np.size(classified[classified==True]))
print('False :',np.size( classified[classified==False]))

True : 526
False : 186


In [19]:
prob = y.eval(session=sess, feed_dict={x:X})
print(prob[0:10])

[[ 0.10784346]
 [ 0.4778609 ]
 [ 0.36739242]
 [ 0.47234526]
 [ 0.10942736]
 [ 0.4718698 ]
 [ 0.29307482]
 [ 0.15082341]
 [ 0.55259395]
 [ 0.91813242]]


In [20]:
print(sess.run(w1))   ### 값 출력
print(sess.run(w2))
print(sess.run(b1))
print(sess.run(b2))

[[ -2.20444393e+00  -6.93261623e-01   7.39510655e-02   8.51382613e-01
    1.05875289e+00   1.36651850e+00   3.31099510e-01  -1.21108606e-01
    1.73991835e+00]
 [  2.80683565e+00  -5.48198581e-01   2.53320575e-01  -3.72775018e-01
   -7.19845533e+00  -1.45676219e+00   5.12836128e-02   6.42255545e-01
   -8.52473319e-01]
 [  3.19025777e-02  -1.62714899e+00   5.12292206e-01  -5.79241574e-01
    1.13982752e-01  -3.63347121e-03  -4.45846289e-01  -1.76358715e-01
   -1.40023434e+00]
 [ -1.73621500e+00   1.23155153e+00  -3.32531571e-01  -1.84215534e+00
    5.92778862e-01   1.55168808e+00  -2.03682780e+00  -1.46071270e-01
   -5.88676095e-01]
 [ -9.85043526e-01   9.60233331e-01   1.16868472e+00   5.79655021e-02
    4.47287321e-01   6.60408199e-01  -9.69808936e-01  -8.38333070e-01
   -1.47859171e-01]
 [  2.33609304e-01  -5.48155785e-01   4.73596543e-01  -2.09362879e-02
    2.09957838e-01   4.03605431e-01   2.12539718e-01   9.56339180e-01
    1.78278697e+00]
 [  6.78589940e-02  -6.42523170e-01  -1.